// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBebGShh_EubRWouqoequa-aamHpg5PQiY',
    appId: '1:567323089797:android:9bbacb2db884e5f999c2ec',
    messagingSenderId: '567323089797',
    projectId: 'fluttersignin-bba22',
    storageBucket: 'fluttersignin-bba22.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa9XF2GgpynV4N8gxsFpsX-84XSR1-Trk',
    appId: '1:567323089797:web:4f146edfd83e942999c2ec',
    messagingSenderId: '567323089797',
    projectId: 'fluttersignin-bba22',
    authDomain: 'fluttersignin-bba22.firebaseapp.com',
    storageBucket: 'fluttersignin-bba22.appspot.com',
    measurementId: 'G-6SB76ZN0GV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHZ61aAikqJmgULVgdyKZB3Kdwr2_Mvl4',
    appId: '1:567323089797:ios:eb3ea8141ce0885899c2ec',
    messagingSenderId: '567323089797',
    projectId: 'fluttersignin-bba22',
    storageBucket: 'fluttersignin-bba22.appspot.com',
    androidClientId: '567323089797-ij83eo526uj3c569tn5vhjoks58rsb01.apps.googleusercontent.com',
    iosClientId: '567323089797-l2qve6j9574rumk3kmplsbhsiv88h3qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHZ61aAikqJmgULVgdyKZB3Kdwr2_Mvl4',
    appId: '1:567323089797:ios:eb3ea8141ce0885899c2ec',
    messagingSenderId: '567323089797',
    projectId: 'fluttersignin-bba22',
    storageBucket: 'fluttersignin-bba22.appspot.com',
    androidClientId: '567323089797-ij83eo526uj3c569tn5vhjoks58rsb01.apps.googleusercontent.com',
    iosClientId: '567323089797-l2qve6j9574rumk3kmplsbhsiv88h3qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZdIE3N6KpqZgvHcC-_vwowmC6uSINWHg',
    appId: '1:567323089797:web:6cf9497c2dcfc8ab99c2ec',
    messagingSenderId: '567323089797',
    projectId: 'fluttersignin-bba22',
    authDomain: 'fluttersignin-bba22.firebaseapp.com',
    storageBucket: 'fluttersignin-bba22.appspot.com',
    measurementId: 'G-2S6MK87BK2',
  );

}